export const baseIcons = [
    'student', 
    'setting', 
    'trophy', 
    'privacy', 
    'alarm outline', 
    'lab', 
    'bug', 
    'code', 
    'sitemap', 
    'protect', 
    'unhide', 
    'random', 
    'retweet', 
    'sign language', 
    'bomb', 
    'sun', 
    'law', 
    'life ring', 
    'anchor', 
    'hand scissors', 
    'snowflake outline', 
    'thermometer empty', 
    'tv', 
    'cube', 
    'asterisk', 
    'database', 
    'plane', 
    'shipping', 
    'umbrella', 
    'fire', 
    'cocktail', 
    'book', 
    'gift', 
    'road', 
    'rocket', 
    'bar', 
    'legal', 
    'area chart', 
    'line chart', 
    'camera retro', 
    'bath', 
    'hourglass empty', 
    'find', 
    'options', 
    'ticket', 
    'copyright', 
    'heartbeat', 
    'at', 
    'eyedropper', 
    'trademark', 
    'hourglass half', 
    'alarm mute', 
    'history', 
    'percent', 
    'hashtag', 
    'shopping basket', 
    'shopping bag', 
    'file excel outline', 
    'barcode', 
    'html5', 
    'fork', 
    'empty star', 
    'heart', 
    'smile', 
    'frown', 
    'star half empty'
];
